### ISSUE TITLE
Rendering error when reducing the crop image

### ISSUE THREAD

**Issue by hyz1992** [VolodymyrLykhonis/image_crop#1]
this is really a great plugin.
but there is a small issue, I can zoom out and move the crop image at the same time, so some times I drag it out of screen, and it won't come back automatically. the result is, screen is black,or rending a wrong texture.

**Comment by VolodymyrLykhonis** [comment]
I've noticed similar. Usually it can be resolved by a user dragging/touching the area. I am planning into looking into it.

**Comment by VolodymyrLykhonis** [comment]
Resolved in [v0.1.2](Resolved in v0.1.2. Please reopen if the issue still persist. https://github.com/VolodymyrLykhonis/image_crop/commit/beb75398f1361659ad4ec98eebcdcfd78e2db086). Please reopen if the issue still persist.
