### ISSUE TITLE
Not cropping images taken from samsung camera

### ISSUE THREAD

**Issue by praneethfdo** [VolodymyrLykhonis/image_crop#14]
This happens as it does not read meta data of the images. A portrait image is saved in landscape orientation and those details are saved as Exif. When a portrait image is given to the cropper it read its height and width in wrong orientation where width > height.

**Comment by cnyunguo** [comment]
I also have this problem. It's very serious. Please pay attention to it.

**Comment by TimonBozzApps** [comment]
Same for me

**Comment by stefanschaller** [comment]
Same !

**Comment by bubu98** [comment]
This issue is not fixed for iOs.

**Comment by VolodymyrLykhonis** [comment]
@bubu98 what is the issue on iOS? This ticket is for Exif information on samsung devices.

**Comment by bubu98** [comment]
> @bubu98 what is the issue on iOS? This ticket is for Exif information on samsung devices.

Hi @VolodymyrLykhonis, when I crop a portrait picture on iOS (with ImageCrop.cropImage) , it is saved as a landscape (I do not have this issue on android).

Thank you for your time.

Regards,

**Comment by VolodymyrLykhonis** [comment]
@bubu98 Yes, please create seperate issue. Thanks.
