### ISSUE TITLE
Errors when trying to crop image

### ISSUE THREAD

**Issue by herrmartell** [VolodymyrLykhonis/image_crop#17]
`W/ExifInterface(28582): Skip the tag entry since data format (ULONG) is unexpected for tag: LightSource
W/ExifInterface(28582): Stop reading file since a wrong offset may cause an infinite loop: 0
I/chatty  (28582): uid=10310(com.refereepro.refereepro_cm) pool-1-thread-1 identical 1 line
W/ExifInterface(28582): Stop reading file since a wrong offset may cause an infinite loop: 0
W/ExifInterface(28582): Skip the tag entry since data format (ULONG) is unexpected for tag: LightSource
W/ExifInterface(28582): Stop reading file since a wrong offset may cause an infinite loop: 0
I/chatty  (28582): uid=10310(com.refereepro.refereepro_cm) pool-1-thread-1 identical 1 line
W/ExifInterface(28582): Stop reading file since a wrong offset may cause an infinite loop: 0`

I have a Samsung Galaxy A50. When trying to crop an image I always get an error, and although I don't know a way to know for sure, it always looks like the image was incorrectly cropped (if cropped at all). Happens exactly the same when trying to crop a picture from the Gallery.

Anyone knows what could be going on?

**Comment by VolodymyrLykhonis** [comment]
Closing as duplicate. https://github.com/VolodymyrLykhonis/image_crop/issues/14
