### ISSUE TITLE
Crash cause call Result methods from a thread other than the main thread

### ISSUE THREAD

**Issue by geumatee** [VolodymyrLykhonis/image_crop#18]
When tried to open image.

`E/AndroidRuntime( 7809): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-12-thread-1
E/AndroidRuntime( 7809): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime( 7809): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:556)
E/AndroidRuntime( 7809): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:129)
E/AndroidRuntime( 7809): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:215)
E/AndroidRuntime( 7809): 	at com.lykhonis.imagecrop.ImageCropPlugin$1.run(ImageCropPlugin.java:120)
E/AndroidRuntime( 7809): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 7809): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 7809): 	at java.lang.Thread.run(Thread.java:764)`

My doctor.
`Flutter (Channel master, v1.5.9-pre.167, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.5.9-pre.167 at C:\flutter
    • Framework revision f5674d7098 (8 hours ago), 2019-05-06 18:32:28 -0700
    • Engine revision ee6412a74d
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 dbe80f3397)`

[look like this issue](https://github.com/flutter/flutter/issues/22024#issuecomment-482247126)

**Comment by VolodymyrLykhonis** [comment]
Fixed with https://github.com/VolodymyrLykhonis/image_crop/commit/1164fbafb88fe9c54ba6b5c16e857159b7b56582

Thanks for reporting this!
