### ISSUE TITLE
Handles are moving the image

### ISSUE THREAD

**Issue by Z6P0** [VolodymyrLykhonis/image_crop#19]
When handles are moved, the image is moved at the same time.
This makes it difficult to select a crop area.
However curiously the image does not move with the bottom-right handle.

**Comment by rdev-software** [comment]
Same here, bottom right is only one correct !

**Comment by VolodymyrLykhonis** [comment]
This was done to make sure the image stays within bounds when they are
changed. It can be improved by not moving it but it's not a blocker.

Will keep this open for future work.

Thanks for reporting it.

**Comment by rdev-software** [comment]
Its really annoying and with really poor UX. At least have a flag option to do so. But basically crop should not affect original image at all. And if so you can use pinch to zoom to affect underlaying layer (image). I may try to update library, as I have one project / client who is interested in this. And if he request such change, I will post changes / fork it...so if you want you can add it as a feature. 

Thx for reply

**Comment by Z6P0** [comment]
Yes please fix the handles behavior, for me the plugin is unusable as it stands.

**Comment by VolodymyrLykhonis** [comment]
Fixed in 9cd25ed8651a057a5876e28a779f69dc3c107f75
