### ISSUE TITLE
How to save crop_image?

### ISSUE THREAD

**Issue by NTMS2017** [VolodymyrLykhonis/image_crop#22]
I need to save cropped image to app temp folder and use later to send via email. So I have a few question.
1) How can I save cropped image to device?
2) Separately I need to take 3 picture and crop the images before send via mail. what is the best and fastest way to save these images? 

thanks

  ```
//TODO: CROP IMAGE
  Future<void> _cropImage(BuildContext context) async {
    final scale = cropKey.currentState.scale;
    final area = cropKey.currentState.area;
    if (area == null) {
      // cannot crop, widget is not setup
      return;
    }

    // scale up to use maximum possible number of pixels
    // this will sample image in higher resolution to make cropped image larger
    final sample = await ImageCrop.sampleImage(
      file: _file,
      preferredSize: (3000 / scale).round(),
    );

    final file = await ImageCrop.cropImage(
      file: sample,
      area: area,
    );
```

**Comment by NTMS2017** [comment]
I am keep getting this error:

**Error:**
```
flutter: ================= File: '/private/var/mobile/Containers/Data/Application/DBE50ECE-D66A-48C6-A1C3-1A15F602B300/tmp/image_crop_A2D9CA93-B387-4DE8-8269-E7CB040422F6-325-00000008F9BEEB4D.jpg'

flutter: Another exception was thrown: FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/DBE50ECE-D66A-48C6-A1C3-1A15F602B300/Documents/File: '/private/var/mobile/Containers/Data/Application/DBE50ECE-D66A-48C6-A1C3-1A15F602B300/tmp/image_crop_A2D9CA93-B387-4DE8-8269-E7CB040422F6-325-00000008F9BEEB4D.jpg'' (OS Error: No such file or directory, errno = 2)

```

**Code:**
```
  //TODO: CROP IMAGE
  Future<void> _cropImage(BuildContext context) async {
    final scale = cropKey.currentState.scale;
    final area = cropKey.currentState.area;
    if (area == null) {
      // cannot crop, widget is not setup
      return;
    }

    // scale up to use maximum possible number of pixels
    // this will sample image in higher resolution to make cropped image larger
    final sample = await ImageCrop.sampleImage(
      file: _file,
      preferredSize: (3000 / scale).round(),
    );

    final file = await ImageCrop.cropImage(
      file: sample,
      area: area,
    );
    print("================= $file");
    setState(() {
      IDCardClass.frontImageFile = file.toString();
      widget.notifyParentFront();
      _corrping = false;
    });
    Navigator.pop(context);


```

**Comment by NTMS2017** [comment]
my main page widget widget.notifyParentFront(); code:

 ```
 // TODO: (5) REFRESH FRONT
  refreshFront() async {
    final _directory = await getApplicationDocumentsDirectory();
    _appDocumentsDirectory = _directory.path;

    setState(() {
      if (IDCardClass.frontImageFile == null) {
        print("IDCardClass.frontImageFile looks like null");
        _frontImageFile = null;
      } else {
        //FILE
        _frontImageFile = new File(
            "${_appDocumentsDirectory + "/" + IDCardClass.frontImageFile}");
      }
    });
  }
```

**Comment by VolodymyrLykhonis** [comment]
This is not a right place for dart questions.

1. The issue you are having is that you are not using right path of the file: `IDCardClass.frontImageFile = file.toString();`. Instead of `toString` you should be using `path` [property](https://api.dartlang.org/stable/2.3.1/dart-io/File/path.html). That's assuming that `IDCardClass.frontImageFile` is a `String`.
2. Once you cropped an image via `ImageCrop.cropImage`, it returns a file in the application directory. The application must have write permissions to local storage to copy this file to its final destination.

**Comment by leeyisoft** [comment]
I added the following code to solve the problem where the “ FileSystemException: Cannot open file”

`
       Future.delayed(Duration(milliseconds: 200)).then((value) {
          sample.delete();
          croppedFile.delete();
        });
`
参考  https://gitee.com/imboy-pub/imboy-flutter/blob/main/lib/component/helper/crop_image.dart
`
  Future<void> _crop(File originalFile) async {
    final crop = cropKey.currentState;
    final area = crop!.area;
    if (area == null) {
      //裁剪结果为空
      print('裁剪不成功');
    }

    await ImageCrop.requestPermissions().then((value) async {
      if (value) {
        final sample = await ImageCrop.sampleImage(
          file: originalFile,
          preferredSize: widget.preferredSize,
        );
        final croppedFile = await ImageCrop.cropImage(
          file: sample,
          area: crop.area!,
        );

        upload(croppedFile);
        Future.delayed(Duration(milliseconds: 200)).then((value) {
          sample.delete();
          croppedFile.delete();
        });
      } else {
        upload(originalFile);
      }
    });
  }
`
