### ISSUE TITLE
ImageStreamLister not found

### ISSUE THREAD

**Issue by xenosis** [VolodymyrLykhonis/image_crop#24]
I am seeing errors in the debug console when i try use Crop.file about a missing image stream listener

Error: Type 'ImageStreamListener' not found.
  ImageStreamListener _imageListener;
  ^^^^^^^^^^^^^^^^^^^
Error: 'ImageStreamListener' isn't a type.

**Comment by VolodymyrLykhonis** [comment]
There was a breaking change in Flutter framework starting in 1.6.6 (or 1.6.5).

If you are on older version of Flutter, try to use image_crop v0.2.1

**Comment by xenosis** [comment]
I'm using the latest version on the stable channel and am seeing this issue

**Comment by VolodymyrLykhonis** [comment]
You need to use older version (not 0.3.0) of image_crop if you are not using flutter 1.6.6 and above.

**Comment by EHBradford** [comment]
I understand about usage of version 0.2.1.   Are there plans to correct the problem?

**Comment by VolodymyrLykhonis** [comment]
This is not a problem. Flutter v1.6.6 made braking changes, thus this
version to support Flutter v1.6.6 and above.
