### ISSUE TITLE
Aspect ratio problem

### ISSUE THREAD

**Issue by roidy** [VolodymyrLykhonis/image_crop#25]
Setting an aspect ratio that is the same as the device screen causes the masking box to fill almost the whole screen and the handles are no longer selectable.

16:10 works fine
![Screenshot_20190706-090703 1](https://user-images.githubusercontent.com/4118048/60753642-dad4c500-9fcd-11e9-8b04-989e47158bba.png)

10:16 fails, you can no longer move the handles
![Screenshot_20190706-090642 1](https://user-images.githubusercontent.com/4118048/60753652-efb15880-9fcd-11e9-93a4-197f04b4b929.png)

**Comment by VolodymyrLykhonis** [comment]
This can be solved by limiting the crop widget area. You can add padding or use container and crop widget as a child.
