### ISSUE TITLE
Image picker is already active error

### ISSUE THREAD

**Issue by NTMS2017** [VolodymyrLykhonis/image_crop#29]
I try to use camera with latest version (image_crop: ^0.3.0) and got an error on Image picker is already active. I used Samsung real device (S7 edge). Any idea?

D/ViewRootImpl@4c27af4[MainActivity](23312): ViewPostIme pointer 1
E/flutter (23312): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null)
E/flutter (23312): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (23312): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (23312): <asynchronous suspension>
E/flutter (23312): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:53:40)
E/flutter (23312): <asynchronous suspension>
E/flutter (23312): #3      _MyAppState._openImage

**Comment by JamesMcIntosh** [comment]
@NTMS2017 Looks like a problem with ImagePicker
https://github.com/flutter/flutter/issues/32315
