### ISSUE TITLE
Add several modes

### ISSUE THREAD

**Issue by jlcool** [VolodymyrLykhonis/image_crop#3]
There should be two modes
The first is to move the zoom image, but the clipping area is fixed.
Second, the image is fixed and the clipping area can be moved.
Then there are some problems.
Image zooming is not sensitive. I have found a code problem. Can I submit it it?
Pictures should not be forced to return, so that the corners are not easily intercepted, or returns should also be returned to the clipping area.

**Comment by VolodymyrLykhonis** [comment]
Hi. I am planning on to work on some of the items. Please feel free to make
a PR. Thank you!

**Comment by VolodymyrLykhonis** [comment]
Resolved in v0.1.2 https://github.com/VolodymyrLykhonis/image_crop/commit/beb75398f1361659ad4ec98eebcdcfd78e2db086. Please reopen if the issue still persist.
