### ISSUE TITLE
Picture orientation is systematically changed to portrait after cropping on iOs devices only

### ISSUE THREAD

**Issue by bubu98** [VolodymyrLykhonis/image_crop#31]
After cropping a picture in landscape, the orientation is systematically changed to portrait.

This problem is only on iOs (AMHA is issue resolved in #14 for Android devices).

**Comment by wwwdata** [comment]
Any updates on this? I can confirm the issue. @VolodymyrLykhonis are you looking into it? Otherwise I could also try to debug this.

**Comment by VolodymyrLykhonis** [comment]
@wwwdata I have not had chance look at this yet. You can definitely give it a shot

**Comment by TranPhuHung98** [comment]
I had this problem too.

**Comment by chukwumaokere** [comment]
I'm also having this problem.

**Comment by igorstr** [comment]
Added PR with fix
https://github.com/VolodymyrLykhonis/image_crop/pull/33

**Comment by bubu98** [comment]
> Added PR with fix
> #33

Thanks <3

**Comment by VolodymyrLykhonis** [comment]
Closing as per https://github.com/VolodymyrLykhonis/image_crop/commit/f4562e1b8e17ed53ee2b641e7b33f8c739bb361e

**Comment by GadepalliAditya1998** [comment]
In my case if i try cropping a picture from gallery then it turns to landscape for some pictures and the crop area that i chose is not being cropped but showing some other region of the picture
