### ISSUE TITLE
Crop image parameter does not accept Image.file(image) expects ImageProvider

### ISSUE THREAD

**Issue by testyourcodenow** [VolodymyrLykhonis/image_crop#36]
When passing uploaded image to the Crop image parameter via Image.file method i get the error: "The argument type 'Image' can't be assigned to the parameter type 'ImageProvider'.dart(argument_type_not_assignable)". in Flutter version v1.9.1+hotfix.5

**Comment by koyadovic** [comment]
Here the same:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale es_ES.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by koyadovic** [comment]
Using `image: FileImage(File(photoPath)),` instead of `image: Image.file(File(photoPath))` the error is gone. I will check if this change works
