### ISSUE TITLE
Initial render of crop area empty

### ISSUE THREAD

**Issue by lukbukkit** [VolodymyrLykhonis/image_crop#5]
Hello,

I've encountered a bug on my OnePlus 5T while using this library.
My phone currently runs Android 9, but this also happens with Android 8.
This bug doesn't appear in the Android emulator (8 and 9).

Bug: After I've choosen a picture, there's nothing displayed in the crop area, until I choose a new picture or request a crop.

Here's a video of the bug: https://youtu.be/ybkYCej60kQ
And other thing I've noticed: When I toggle the debug render mode, the image appears.
Here's a video of that: https://youtu.be/GvGAfBsTwxw

Thanks for the useful library 👍

**Comment by VolodymyrLykhonis** [comment]
Does this appear on v0.1.2?

**Comment by LukBukkit** [comment]
Yes is does.
I did a little bit of investigation and it seems that the issue is caused by the call of [`addPostFrameCallback`](https://github.com/VolodymyrLykhonis/image_crop/blob/9bea6cc2521f2c5aae7187f293cbf347fcd325bc/lib/src/crop.dart#L218) in the `_updateImage` function.
