### ISSUE TITLE
i want moving cropper

### ISSUE THREAD

**Issue by maseunghwa** [VolodymyrLykhonis/image_crop#8]
hi genius developer. 

i want make a moving cropper.  please provide that function ??

please tell me the good news.

thank you ^^

**Comment by maseunghwa** [comment]
1. If I touch, the grid must move
2.If you cut a corner, the wrong place is cut off.  maybe picture was rotated save from device.

**Comment by VolodymyrLykhonis** [comment]
This plugin is designed to move actual image not a grid. A grid represents
cropping area.

If that makes sense.

**Comment by maseunghwa** [comment]
Please put the option?
picture is stop  and grid moving!!  

i will send to email  tomorrow~

**Comment by VolodymyrLykhonis** [comment]
Sorry, this is not supported. As per my previous comment, this plugin
functions differently. Though it achieves same thing, cropping the image.
